
tap 'homebrew/bundle'

brew "git"
brew "node"
brew "zsh"
brew "bat"
brew "eza"
brew "fzf"
brew "zoxide"
brew "ripgrep"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "neovim"
brew "fd"

# cask "font-fira-code"
# cask "font-fira-code-nerd-font"
# cask "font-jetbrains-mono"
# cask "font-jetbrains-mono-nerd-font"

# cask "iterm2"
# cask "visual-studio-code"
# cask "arc"
# cask "notion"
# cask "notion-calendar"