alias cd="z" 
alias cat="bat --style=numbers --color=always"
alias ls="eza --icons=always"
alias ll="eza -l --icons=always" 
alias l="eza -l --icons=always" 
alias la="eza -la --icons=always "
alias tree="eza --all --tree --level=3 --icons=always "
alias cls="clear" 
alias vsc="code ." 
alias sql="mysqlsh" 
