alias fzf="fzf --height 55% --border"
alias ls="eza --icons=always"
alias perm="eza --icons=always --long --no-user --no-filesize --no-time"
alias la="eza --icons=always --long --all"
alias l="eza --icons=always --long"
alias tree="eza --icons=always --tree --color=always --level=4 --group-directories-first"
alias cd="z"